# Generated by Django 5.0.2 on 2024-07-15 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songmanager", "0003_alter_songslist_playlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(default="", max_length=100)),
                ("song", models.FileField(upload_to="audios/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dislike",
                    models.ManyToManyField(
                        blank=True, related_name="nlikes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "favourite",
                    models.ManyToManyField(
                        blank=True, related_name="fav", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "playlist",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="songmanager.playlist"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SongsList",
        ),
    ]
