# Generated by Django 5.0.2 on 2024-07-15 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songmanager", "0004_songs_delete_songslist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songs",
            name="dislike",
        ),
        migrations.RemoveField(
            model_name="songs",
            name="favourite",
        ),
    ]
