# Generated by Django 5.0.2 on 2024-07-15 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songmanager", "0005_remove_songs_dislike_remove_songs_favourite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="songs",
            name="dlike",
            field=models.ManyToManyField(
                blank=True, related_name="dlikes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
